// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace FACTS.GenericBooking.Repository.Postgres.Entities
{
    [Table("sys_log")]
    public partial class SysLog
    {
        [Key]
        [Column("id")]
        public int Id { get; set; }
        [Column("log_level")]
        [StringLength(1000)]
        public string LogLevel { get; set; }
        [Column("log_logger")]
        [StringLength(255)]
        public string LogLogger { get; set; }
        [Column("log_message")]
        public string LogMessage { get; set; }
        [Column("log_exception")]
        public string LogException { get; set; }
        [Column("app_type")]
        [StringLength(500)]
        public string AppType { get; set; }
        [Column("device_name")]
        [StringLength(25)]
        public string DeviceName { get; set; }
        [Column("log_date")]
        public DateTime LogDate { get; set; }
    }
}